apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
  name: {{ .Chart.Name }}
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.deployment.nodePool }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: MANAGER_RPC_ADDR
              valueFrom:
                configMapKeyRef:
                  key: managerRpcAddr
                  name: {{ .Chart.Name }}
            - name: ADDR
              value: 0.0.0.0:{{ .Values.service.externalPort }}
          resources: {}
