apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: api
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          resources:
            cpu:
            memory:
          # 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          resources:
            cpu:
            memory:
          imagePullPolicy: Always
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances=videocoin-183500:us-west1:testing=tcp:3306
            - term_timeout=9s
        - name: manager
          image: us.gcr.io/videocoin-183500/manager:testing
          imagePullPolicy: Always
          env:
            - name: INGEST_HLS_URL
              valueFrom:
                configMapKeyRef:
                  key: ingest_hls_url
                  name: config
            - name: INGEST_RTMP_URL
              valueFrom:
                configMapKeyRef:
                  key: ingest_rtmp_url
                  name: config
            - name: BASE_STREAM_URL
              valueFrom:
                configMapKeyRef:
                  key: base_stream_url
                  name: config
            - name: STORAGE_URL
              valueFrom:
                configMapKeyRef:
                  key: base_storage_url
                  name: config
            - name: BLOCKCHAIN_URL
              valueFrom:
                configMapKeyRef:
                  key: blockchain_url
                  name: config
            - name: SMCA
              valueFrom:
                configMapKeyRef:
                  key: smca
                  name: config
            - name: SQL_URI
              valueFrom:
                configMapKeyRef:
                  key: sql_uri
                  name: config
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  key: image_url
                  name: config
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: nats_url
                  name: config
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: cluster_id
                  name: config
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manager-password
                  key: password
            - name: NATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: token
            - name: KEY_FILE
              value: keys/manager.key
            - name: RPC_ADDR
              value: 0.0.0.0:50051
            - name: PROXY_PORT
              value: 0.0.0.0:50053
            - name: HASH_KEY
              valueFrom:
                secretKeyRef:
                  name: secrethash
                  key: hash
          resources: {}
