kind: Service
apiVersion: v1
metadata:
  name: hookd
spec:
  type: LoadBalancer
  loadBalancerIP: 35.185.249.130
  selector:
    app: hookd
  ports:
  - name: tcp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: rtmp
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: ingest
    protocol: TCP
    port: 8888
    targetPort: 8888

