apiVersion: apps/v1
kind: Deployment
metadata:
  name: hookd
  labels:
    app: hookd
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: hookd
  template:
    metadata:
      labels:
        app: hookd
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: api
      containers:
        - name: hookd
          image: us.gcr.io/videocoin-183500/hookd:testing
          imagePullPolicy: Always
          resources:
          env:
            - name: ADDR
              value: 0.0.0.0:8888
